name: Thesis CI

on:
    push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Generate PDF document
              uses: hspaans/latexmk-action@v1
              with:
                format: pdf
                filename: main.tex
            - name: Upload PDF
              uses: actions/upload-artifact@v3
              with:
                name: Master Thesis
                path: ./main.pdf
