name: Thesis CI

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'references.bib'

jobs:
    build:
        runs-on: ubuntu-latest
        env: 
            CI_COMMIT_MESSAGE: Build Pdf
            CI_COMMIT_AUTHOR: CI
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Generate PDF document
              uses: hspaans/latexmk-action@v1
              with:
                format: pdf
                filename: main.tex
            - name: Push PDF
              if: github.event_name == 'push'
              run: |
                git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
                git config --global user.email "BennoGreg@users.noreply.github.com"
                git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
                git push
              
